### ISSUE TITLE
Investigate MPS support

### ISSUE THREAD

**Issue by justusschock** [Lightning-AI/metrics#1044]
## 🚀 Feature

We need to investigate support for the new 'mps' backend. I assume this will not be working, as many operations are not yet supported. However, we should give it a try and currently raise an error if necessary.

For the record: https://github.com/PyTorchLightning/pytorch-lightning/pull/13123

**Comment by saikatkumardey** [comment]
I am facing an [issue](https://github.com/Lightning-AI/lightning/pull/13123#issuecomment-1211859657) on MPS.

**Comment by justusschock** [comment]
So far we don't officially support MPS for metrics. Most of the stuff should work, however. For the failing ops, we can only wait for official support from the pytorch side. Did you try tu run with `PYTORCH_ENABLE_MPS_FALLBACK=1`?
