### ISSUE TITLE
"Weighted" JaccardIndex ignore_index throws RuntimeError

### ISSUE THREAD

**Issue by dkermany** [Lightning-AI/metrics#1119]
## 🐛 Bug

I am trying to calculated a weighted Jaccard score for the COCO dataset

When I try to pass the options _average="weighted"_ and _ignore_index=0_ at the same time with _num_classes=81_, I get the following error:

_RuntimeError: The size of tensor a (81) must match the size of tensor b (80) at non-singleton dimension 0_

This error is not reproduced when using other values of _average_ or not setting the _ignore_index_ parameter.

#### Code sample
```py
import torch
import torchmetrics

logits = torch.randint(0, 81, (100, 256, 256))
targets = logits[:]

j = torchmetrics.functional.jaccard_index(
    preds,
    targets,
    num_classes=81,
    average="weighted",
    ignore_index=0,
)
```
#### Output
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    j = torchmetrics.functional.jaccard_index(
  File "C:\Users\danie\.virtualenvs\BoneSegmentation-dpCXn3BL\lib\site-packages\torchmetrics\functional\classification\jaccard.py", line 164, in jaccard_index
    return _jaccard_from_confmat(confmat, num_classes, average, ignore_index, absent_score)
  File "C:\Users\danie\.virtualenvs\BoneSegmentation-dpCXn3BL\lib\site-packages\torchmetrics\functional\classification\jaccard.py", line 91, in _jaccard_from_confmat
    return torch.sum(weights * scores)
RuntimeError: The size of tensor a (81) must match the size of tensor b (80) at non-singleton dimension 0
```

### Environment

- Libraries installed with pipenv
- Versions:
    - Python == 3.8.10
    - Torchmetrics == 0.9.1
    - Torch == 1.11.0+cu113
- Recreated on both Windows and Ubuntu

**Comment by Maitreyapatel** [comment]
To add on this issue, there is another bug when `ignore_index>num_classes` it throws following error:
`RuntimeError: shape '[81, 81]' is invalid for input of size 6642`

Code sample:
```
import torch
import torchmetrics

logits = torch.randint(0, 81, (100, 256, 256))
targets = torch.randint(0, 82, (100, 256, 256))

j = torchmetrics.functional.jaccard_index(
    logits,
    targets,
    num_classes=81,
    ignore_index=82,
)
```

There should be a better way to handle the `ignore_index` within `confusion_metrix.py` as well.

**Comment by SkafteNicki** [comment]
Issue will be fixed by classification refactor: see this issue https://github.com/Lightning-AI/metrics/issues/1001 and this PR https://github.com/Lightning-AI/metrics/pull/1195 for all changes

Small recap: This issue describes two issues:
* First one that using `average="weighted"` and `ignore_index=0` results in a runtime error.
* Secondly that `ignore_index` cannot be outside the `[0, num_classes-1]` range.

Happy to report that both issues have been solved in the refactor. Thus using the new multiclass version of the metric:
```python
from torchmetrics.functional import multiclass_jaccard_index
import torch

preds= torch.randint(0, 81, (100, 256, 256))
target = preds[:]

# no error is raised
multiclass_jaccard_index(logits, targets, num_classes=81, ignore_index=0, average='weighted')  # tensor(1.0000)
multiclass_jaccard_index(logits, targets, num_classes=81, ignore_index=82, average='weighted')  # tensor(1.0000)
```
which give the correct result. Issue will be closed when https://github.com/Lightning-AI/metrics/pull/1195 is merged.
