### ISSUE TITLE
Links in readme are broken

### ISSUE THREAD

**Issue by SkafteNicki** [Lightning-AI/metrics#1123]
## 🐛 Bug

All these links are broken:
https://github.com/Lightning-AI/metrics/blob/820dd0fc912239716472be4e9112178da30e8411/README.md?plain=1#L274-L311
We should either completely drop the section, only mention what domains we cover or fix the links.

### To Reproduce

Steps to reproduce the behavior...

### Environment

- TorchMetrics version (and how you installed TM, e.g. `conda`, `pip`, build from source):
- Python & PyTorch Version (e.g., 1.0):
- Any other relevant information such as OS (e.g., Linux):

**Comment by Borda** [comment]
> We should either completely drop the section, only mention what domains we cover or fix the links.

I am fine with it
