### ISSUE TITLE
mIoU

### ISSUE THREAD

**Issue by Lee-Akita** [Lightning-AI/metrics#1124]
Where is the semantic segmentation mIou?

**Comment by luca-medeiros** [comment]
You can find the segm key here:
https://github.com/Lightning-AI/metrics/blob/fbdd1465efff06b2119b30a4dbf90cf83e4e620d/src/torchmetrics/detection/mean_ap.py#L227

**Comment by YangLeiSX** [comment]
I think it is ok to use jaccard_index to calculate mIoU and IoU over each class in segmentation task.

My code for 5-classes segmentation is as below.

```python
import torch
import torchmetrics

preds = torch.randn(2, 5, 128, 256)
target = torch.randint(5, (2, 128, 256))

miou = torchmetrics.functional.jaccard_index(preds, target, num_classes=5)
print(miou)
ious = torchmetrics.functional.jaccard_index(preds, target, num_classes=5, average=None)
print(ious)

```
