### ISSUE TITLE
R2Score does not match sklearn.metrics.r2_score

### ISSUE THREAD

**Issue by adamklie** [Lightning-AI/metrics#1161]
## 🐛 Bug

The `torchmetrics.R2Score` outputs are not consistently matching what I get from `sklearn.metrics.r2_score`. When I test on the tensors and arrays from both of the docs pages they are equal, but when I use my own data I get a large negative number from torchmetrics and a reasonable one from sklearn.

#### Code sample

```py
import torch
from torchmetrics import R2Score
import sklearn.metrics

target = torch.tensor([3, -0.5, 2, 7])
preds = torch.tensor([2.5, 0.0, 2, 8])
tm_r2score = R2Score()
print(tm_r2score(preds, target))

y_true = [3, -0.5, 2, 7]
y_pred = [2.5, 0.0, 2, 8]
print(sklearn.metrics.r2_score(y_true, y_pred))

uno = torch.tensor(sdata_train["log(max_activity)_SCALED"].values) # 7946 values
dos = torch.tensor(sdata_train["log(max_activity)_SCALED_PREDICTIONS"].values) # 7946 values
print(tm_r2score(uno, dos))

uno_x, dos_x = uno.numpy(), dos.numpy()
print(sklearn.metrics.r2_score(uno_x, dos_x))
```
```
>>> tensor(0.9486)  # dummy data torchmetrics out
>>> 0.9486081370449679  # dummy data sklearn out
>>> tensor(-17.8863) # my data torchmetrics out
>>> 0.16492233358169228 # my data sklearn out
```

### Expected behavior

I would expect these to be equal, and based on a scatterplot of the true vs predicted, I would assume sklearn is correct. 
![image](https://user-images.githubusercontent.com/23622847/181353560-fae29f41-269c-47e2-9a10-d29c3e570979.png)

When I log the R2Score in a PL model over training I also see these large negative values for train.
![image](https://user-images.githubusercontent.com/23622847/181353977-626c908f-e7a3-48b5-8742-76a64b4d5d66.png)

### Environment

TorchMetrics installed from pip v0.9.3
Python 3.7.12, PyTorch 1.11.0
Linux OS

### Additional context

Am I misunderstanding what R2Score is doing?

**Comment by SkafteNicki** [comment]
Hi @adamklie,
Could you please provide us with some testing data that creates this discrepancy between our implementation and sklearns?

**Comment by giusmatera** [comment]
Hi, to complement here, I found a very similar issue:

I have 

>             def test_step(self, batch, batch_idx):
> 
>                 batch = batch.to(torch.float32)
> 
>                 pooled_output = batch[
>                     :, :-1
>                 ].float()  # All columns except the last
>                 targets = batch[:, -1].float()
> 
>                 predictions = self(pooled_output).squeeze(-1)
> 
>                 score_r2 = self.test_r2(predictions, targets)  # Compute R2
>                 self.log("test_r2", score_r2, on_epoch=True)
> 
>                 return score_r2

but the test r2 score this step gives differs from what I retrieve directly from predictions and actual values. Also, torchmetrics and sklearn r2 functions match in the latter task. How come? Thanks a lot.
