### ISSUE TITLE
Typo in the docstring in precision_recall_curve.py

### ISSUE THREAD

**Issue by saikatkumardey** [Lightning-AI/metrics#1180]
There's a [typo](https://github.com/Lightning-AI/metrics/blob/58e7ac124ca8800c507558c5b0b477e5fa38a2af/src/torchmetrics/functional/classification/precision_recall_curve.py#L29) in the URL mentioned in the docstring.

Thanks!

**Comment by barufa** [comment]
Hi, I would like to contribute to this issue. I know it's just a typo, but it would be a good way to get involved with the community and learn more about how new PRs are handled.
