### ISSUE TITLE
Cannot import perplexity

### ISSUE THREAD

**Issue by ananyahjha93** [Lightning-AI/metrics#1188]
## 🐛 Bug

Cannot import perplexity or other metrics under torchmetrics.text

### To Reproduce

```
import torchmetrics
from torchmetrics.text import Perplexity
from torchmetrics.text.perplexity import Perplexity

metric = torchmetrics.Perplexity()
```

None of the above imports work

### Environment

- TorchMetrics version (and how you installed TM, e.g. `conda`, `pip`, build from source): 0.9.3 installed using pip
- Python & PyTorch Version (e.g., 1.0): 1.12.0+cu116
- Any other relevant information such as OS (e.g., Linux): WSL

**Comment by ananyahjha93** [comment]
@SkafteNicki

**Comment by Borda** [comment]
> @SkafteNicki @Borda is metrics not actively maintained anymore? quite a few open issues

you are more than hapu to help them resolved :)

**Comment by Borda** [comment]
@ananyahjha93 pls see the release notes and eventually changelog, the `Perplexity` was not released yet, so you need to install it from source... :rabbit: 
https://github.com/Lightning-AI/metrics/blob/13f19e52bda180581b6aede493cf756ccd700cd8/CHANGELOG.md?plain=1#L17

**Comment by SkafteNicki** [comment]
@ananyahjha93 just to add: basically all my time is dedicated to the classification refactor #1001.
This is the reason why many issues are basically just on hold onto that is done.
