### ISSUE TITLE
Incorrect inputs requirements for AUROC

### ISSUE THREAD

**Issue by pme0** [Lightning-AI/metrics#1208]
## 🐛 Bug

The `torchmetrics.AUROC` [documentation](https://torchmetrics.readthedocs.io/en/stable/classification/auroc.html?highlight=auroc) states that
> - num_classes (Optional [int]) – integer with number of classes for multi-label and multiclass problems. **Should be set to None for binary problems**

and the `torchmetrics.ROC.update` documentation states that
> preds (Tensor) – Predictions from model

The two problems I find are:
1. `num_classes=None` does not work for binary problems;
2. `preds` is not clearly defined; it works for predicted probabilities but not for predicted classes;

### To Reproduce
```
import torchmetrics
import torch

probabilities = torch.tensor([
    [0.01, 0.99],
    [0.01, 0.99],
    [0.01, 0.99],
    [0.01, 0.99],    
    [0.01, 0.99],
    [0.01, 0.99],
    [0.99, 0.01],
    [0.99, 0.01],
])
predictions = torch.argmax(probabilities, dim=1)
targets = torch.tensor([1, 1, 0, 0, 0, 0, 0, 0])
```

**(1) using `predicted classes` and `num_classes=None`**
```
auroc = torchmetrics.AUROC(num_classes=None)
auroc.update(predictions, targets)
auroc.compute()

> ValueError: Detected input to `multiclass` but you did not provide `num_classes` argument
```
**(2) using `predicted classes` and `num_classes=2`**
```
auroc = torchmetrics.AUROC(num_classes=2)
auroc.update(predictions, targets)
auroc.compute()

> IndexError: tuple index out of range
```

**(3) using `predicted probabilities` and `num_classes=None`**
```
auroc = torchmetrics.AUROC(num_classes=None)
auroc.update(probabilities, targets)
auroc.compute()

> ValueError: Detected input to `multiclass` but you did not provide `num_classes` argument
```

**(4) using `predicted probabilities` and `num_classes=2`**
```
auroc = torchmetrics.AUROC(num_classes=None)
auroc.update(probabilities, targets)
auroc.compute()

> tensor(0.6667)  # works
```

**Conclusion:**
- From (1) and (3) **`num_classes=None` does not work for binary problems**, whether predicted classes or predicted probabilities are used - contrary to documentation;
- From (3) and (4): **predicted probabilities- not classes - must be used together with `num_classes`** , which the documentation does not make clear;

### Environment

- TorchMetrics 0.9.3
- Python 3.9.4
- PyTorch 1.12.1+cu102
- Linux

**Comment by SkafteNicki** [comment]
Hi @pme0,
Thanks for raising this issue. I can report that this issue will be solved by the classification refactor which is currently ongoing and will be finalized in this PR #1195. Example after refactor:
```python
import torchmetrics
import torch
probabilities = torch.tensor(
     [
         [0.01, 0.99],
         [0.01, 0.99],
         [0.01, 0.99],
         [0.01, 0.99],
         [0.01, 0.99],
         [0.01, 0.99],
         [0.99, 0.01],
         [0.99, 0.01],
   ]
)
predictions = torch.argmax(probabilities, dim=1)
targets = torch.tensor([1, 1, 0, 0, 0, 0, 0, 0])
metric = torchmetrics.classification.BinaryAUROC()
metric.update(predictions, targets)
metric.compute() # tensor(0.6667)
```
