### ISSUE TITLE
How not to compute a metric at each call of the `update`?

### ISSUE THREAD

**Issue by celsofranssa** [Lightning-AI/metrics#1217]
I couldn't find it in the documentation (although I've seen it already) where it's specified how to compute a metric only when the `compute` method is called (and not every call of the `update` method).

**Comment by SkafteNicki** [comment]
Hi @celsofranssa,
I am not sure I understand the question. If you just call `update` the metric will not call `compute`. If you call `forward` then it is correct that the metric calls both `update` and `compute`.

**Comment by celsofranssa** [comment]
> Hi @celsofranssa, I am not sure I understand the question. If you just call `update` the metric will not call `compute`. If you call `forward` then it is correct that the metric calls both `update` and `compute`.

That was the reason. Then I have to call only compute.

**Comment by SkafteNicki** [comment]
You were probably looking for the `compute_on_step` argument which where deprecated in v0.8 (https://github.com/Lightning-AI/metrics/pull/792) and removed in v0.9. Setting this argument to `False` meant that `forward` would just call `update` and not also `compute`.
Closing the issue.

**Comment by celsofranssa** [comment]
> You were probably looking for the `compute_on_step` argument which where deprecated in v0.8 (#792) and removed in v0.9. Setting this argument to `False` meant that `forward` would just call `update` and not also `compute`. Closing the issue.

Exactly.
