### ISSUE TITLE
`list index out of range` in `_sync_dist`

### ISSUE THREAD

**Issue by geoffrey-g-delhomme** [Lightning-AI/metrics#1218]
## 🐛 Bug

`list index out of range` out of range error when using a `list` state with a `default=[]`.

### To Reproduce

`self.add_state("p_true_positives", default=[], dist_reduce_fx="cat")`

when no value is added during update, it raises a list index out of range when hitting:

`if isinstance(output_dict[attr][0], Tensor):` in metric.py (l. 374).

#### Code sample

See above

### Expected behavior

Just add a len() > 0 check before

### Environment

- TorchMetrics version (and how you installed TM, e.g. `conda`, `pip`, build from source): 0.9.3, installed with pip
- Python & PyTorch Version (e.g., 1.0): torch 1.12.1 / python 3.10.4
- Any other relevant information such as OS (e.g., Linux): Linux

**Comment by stancld** [comment]
Hi @geoffrey-g-delhomme, can you share some minimal reproducible code please :]
