### ISSUE TITLE
Metrics fail to reduce across devices in PL when `multidim_average='samplewise'`

### ISSUE THREAD

**Issue by XiaomoWu** [Lightning-AI/metrics#1229]
## 🐛 Metrics fail to reduce across devices in pytorch-lightning when multidim_average='samplewise' (torchmetrics: master/v0.10dev)

Accuracy fails to compute when 
1. doing a multi-dimensional, multi-class classification task, and
1. using pytorch-lightning, and 
2. having multiple devices (e.g., >=2GPUs)

### To Reproduce

First, create a boring model and dataloaders. The following example is a "multi-class, multi-dimensional" classification task.

> Note we let `multidim_average='samplewise'` when we initialize `self.val_acc` in the following code.

```python
# shape:
#     N: number of samples
#     C: number of classes
#     L: sequence length per sample
#     D: embedding dimension

#     input: (N, L, D) where N=64, L=32, D=768

#     preds: (N, C, L) where N=64, C=16, L=32
#     target: (N, C) where N=64, C=16

import pytorch_lightning as pl
import torch

from pytorch_lightning.demos.boring_classes import BoringDataModule, BoringModel
from pytorch_lightning import LightningModule, Trainer
from torch import Tensor
from torch.utils.data import DataLoader, TensorDataset
from torchmetrics.classification import MulticlassAccuracy

class BoringModel(LightningModule):
    def __init__(self) -> None:
        super().__init__()
        self.layer = torch.nn.Linear(768, 16)

        # validation metrics from torchmetrics
        self.val_acc = MulticlassAccuracy(num_classes=16, average='micro', multidim_average='samplewise', ignore_index=-100)
        print(f'{self.val_acc=}')

    def configure_optimizers(self):
        return torch.optim.Adam(self.layer.parameters())

    def forward(self, batch):
        pass

    def training_step(self, batch, batch_idx: int):
        preds = self.layer(batch).transpose(1, 2)  # (N, C, S)
        target = torch.randint(0, 16, (preds.shape[0], preds.shape[2]), dtype=torch.long) \
            .to(preds.device)  # (N, L)

        loss = torch.nn.functional.cross_entropy(preds, target)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx: int):

        preds = self.layer(batch).transpose(1, 2)  # (N, C, D)
        target = torch.randint(0, 16, (preds.shape[0], preds.shape[2]), dtype=torch.long) \
            .to(preds.device)  # (N, L)

        # print(f'{preds.shape=}')
        # print(f'{target.shape=}')

        # update validation metrics
        self.val_acc.update(preds, target)
        # self.log('val/acc', self.val_acc, on_step=False, on_epoch=True)
    
    def validation_epoch_end(self, outputs):
        self.log('val/acc', self.val_acc.compute())
        self.val_acc.reset()



# init dataloader
dataset = TensorDataset(torch.rand(64, 32, 768))[0]
dataloader = DataLoader(dataset, batch_size=8, num_workers=0)

# init model
model = BoringModel()

trainer = Trainer(max_epochs=10, accelerator='gpu', devices=2, strategy='ddp', check_val_every_n_epoch=1)
trainer.fit(model=model, train_dataloaders=dataloader, val_dataloaders=dataloader)
```

I get the error:
```log
ValueError: `self.log(val/acc, tensor([0.0625, 0.0312], device='cuda:1'))` was called, but the tensor must have a single element. You can try doing `self.log(val/acc, tensor([0.0625, 0.0312], device='cuda:1').mean())`
```

However, if I use `multidim_average='global'`, the training is successful. The problem is, though, that I want the extra dimensions to be reduced in a "samplewise" way instead of "global."

### Environment

- TorchMetrics version: **0.10dev0**
- Python version: 3.9
- Pytorch lightning version: 1.7.6
- OS: Ubuntu 22.04

**Comment by SkafteNicki** [comment]
Hi @XiaomoWu,
Thanks for raising this issue. The metric seems to do exactly what it is supposed to. When setting `multidim_average='samplewise' it means that the metric will be calculated per sample and returned for each sample.

The relevant documentation can be found here:
https://torchmetrics.readthedocs.io/en/latest/classification/accuracy.html#multiclassaccuracy
Especially the returns section is relevant:
![image](https://user-images.githubusercontent.com/24896311/191749533-7468c85a-0783-4b06-8b21-5a36f4956c06.png)
For
```python
MulticlassAccuracy(num_classes=16, average='micro', multidim_average='samplewise', ignore_index=-100)
```
this metric will return a tensor that have shape `(N,)` where `N` is the number of samples. 
What you probably want to do is further reduce the result (as indicated in the error message) by changing your code to
```python
    def validation_epoch_end(self, outputs):
        self.log('val/acc', self.val_acc.compute().mean())
        self.val_acc.reset()
```
Closing issue.

**Comment by XiaomoWu** [comment]
Thank you, @SkafteNicki! Yes, the documentation is very clear. Good job on the refactoring!
