### ISSUE TITLE
Unable to unpickle a MatthewsCorrCoef saved object

### ISSUE THREAD

**Issue by okbalefthanded** [Lightning-AI/metrics#1260]
## 🐛 Bug

Matthews Correlation coefficient requires a positional argument num_classes, so it raises a TypeError:
missing 1 required positional argument: 'num_classes'

### To Reproduce

Steps to reproduce the behavior...

The error is reported in this colab notebook :
https://colab.research.google.com/drive/1UvhPyPbzpF61SY-51ti8R_O-Vc2FP-vO?usp=sharing

### Expected behavior

We expect the same behaviour as in v 0.9.3.

### Environment

- TorchMetrics version : 0.10.0, installed using pip
- Python & PyTorch Version: 3.7.14, 1.12.1+cu113
- google Colab

**Comment by stancld** [comment]
@SkafteNicki

**Comment by SkafteNicki** [comment]
Hi @okbalefthanded, thanks for raising this issue.
Happy to report that it has already been solve in PR #1250. To fix the issue you can upgrade to master for now:
```bash
pip install https://github.com/Lightning-AI/metrics/archive/master.zip
```
or wait until the next bugfix release.
Closing issue.
