### ISSUE TITLE
Add Uncertainty coefficient (Theil's U)

### ISSUE THREAD

**Issue by stancld** [Lightning-AI/metrics#1273]
## 🚀 Feature

Add uncertainty coefficient

In [statistics](https://en.wikipedia.org/wiki/Statistics), the uncertainty coefficient, also called proficiency, entropy coefficient or Theil's U, is a measure of nominal [association](https://en.wikipedia.org/wiki/Association_(statistics)). (Source: https://en.wikipedia.org/wiki/Uncertainty_coefficient)

### Motivation

Add correlation metrics specific to categorical variables

### Additional context

Nice blog post on this: https://towardsdatascience.com/the-search-for-categorical-correlation-a1cf7f1888c9

See #1298

**Comment by shenoynikhil** [comment]
I can take this up!

**Comment by stancld** [comment]
@shenoynikhil Great, thanks! I've assigned this issue to you! Feel free to open a PR (or draft PR) once you have anything ready :]
