### ISSUE TITLE
SSIM returns incorrect results under mixed-precision training

### ISSUE THREAD

**Issue by tijiang13** [Lightning-AI/metrics#1290]
## 🐛 Bug
SSIM returns incorrect results under mixed-precision training

### To Reproduce

```
import torch
from torchmetrics.functional import structural_similarity_index_measure

zeros = torch.zeros(1, 3, 540, 540, device="cuda")
ones = torch.ones(1, 3, 540, 540, device="cuda")
with torch.autocast("cuda"):
      # prints 1.3245 instead of 1
      print(structural_similarity_index_measure(zeros, zeros, data_range=1.0)) 

      # print 0.9997 instead of 1
      print(structural_similarity_index_measure(ones, ones, data_range=1.0)) 
```

### Expected behavior

ssim returns 1.0

### Environment

- torchmetrics version: tested with 0.6.0 and 0.10.0, both return wrong results
- Python==3.8.10, Pytorch==1.12.1+cu116 (also tested on 1.10)

**Comment by SkafteNicki** [comment]
Hi @tijiang13, thanks for raising this issue.
I created PR #1291 which will fix this. For the example you have provided
```python
with torch.autocast("cuda"):
      print(structural_similarity_index_measure(zeros, zeros, data_range=1.0)) 
```
gives 1.0002 instead of 1.3245 (which is as close as we probably get when things gets casted to `torch.half`) and for
```python
with torch.autocast("cuda"):
      print(structural_similarity_index_measure(ones, ones, data_range=1.0))
```
it gives 1.0000 as expected.
