### ISSUE TITLE
`MulticlassAccuracy` should not require `num_classes`

### ISSUE THREAD

**Issue by davidgilbertson** [Lightning-AI/metrics#1336]
## 🚀 Feature

In version `0.10.0`, I can do `accuracy(preds, target)` and get a score. The underlying code works out what I want, giving me `(preds.argmax(dim=-1) == target).float().mean()`.

But I get a warning saying that I need to use `MulticlassAccuracy` now, which is fine, but when I do, I don't have the same sensible defaults I had before; I get an error if I don't provide `num_classes`.

Can't this class just use the same logic already in `_input_format_classification` to infer `num_classes` from `preds.shape`? Or even better, not _require_ the value in cases where the value is never used? (I haven't been through code, but I assume if I call `torchmetrics.functional.classification.multiclass_accuracy` without specifying optional parameters, the `num_classes` value isn't actually required).

### Motivation

Sensible defaults, not requiring the user to provide information to the module that the module could reasonably infer on its own.

### Pitch

Probably clear from above?

**Comment by zhutmost** [comment]
Have the same issue. 👀 
Will this be solved soon?

**Comment by davidgilbertson** [comment]
If this behaviour is by design, there are a bunch of examples (e.g. [this page](https://torchmetrics.readthedocs.io/en/stable/pages/lightning.html)) in the docs like this:
```py
class MyModule(LightningModule):
    def __init__(self):
        ...
        self.train_acc = torchmetrics.Accuracy(task='multiclass')
        self.valid_acc = torchmetrics.Accuracy(task='multiclass')
```

That should be updated to reflect the fact that you need to pass in the number of classes to your module, and pass that through to the metric to get it to work:
```py
class MyModule(LightningModule):
    def __init__(self, num_classes):
        ...
        self.train_acc = torchmetrics.Accuracy(task='multiclass', num_classes=num_classes)
        self.valid_acc = torchmetrics.Accuracy(task='multiclass', num_classes=num_classes)
```
