### ISSUE TITLE
Add Minkowski distance

### ISSUE THREAD

**Issue by stancld** [Lightning-AI/metrics#1345]
## 🚀 Feature

Add Minkowski distance, which is a metric that can be considered as a generalization of Euclidean and Manhattan distance

### Additional context
https://en.wikipedia.org/wiki/Minkowski_distance

**Comment by clueless-skywatcher** [comment]
Hi everyone. If this is still open, I would like to take this up. This is my first time to open source contributions and I feel this should be a good start.
