### ISSUE TITLE
Squared LogRatio Metric

### ISSUE THREAD

**Issue by jsappl** [Lightning-AI/metrics#1364]
## 🚀 Squared LogRatio Metric

A metric primarily designed for measuring forecast accuracy given forecasts $F_t > 0$ and actual values $A_t > 0$:

$$\frac{1}{n} \sum_{t=1}^n \ln \Big( \frac{F_t}{A_t} \Big)^2$$

![main](https://user-images.githubusercontent.com/10909765/204646264-30f163d0-8346-4a42-b950-2d93911af83c.png)

### Motivation

Very often forecast accuracy is measured with the mean absolute percentage error (MAPE):
$$\frac{1}{n} \sum_{t=1}^n \Big| \frac{A_t - F_t}{A_t} \Big|.$$
However, there are two issues:
- The MAPE is not symmetric. For all $A_t > F_t > 0$ it does not exceed 100%. For all $A_t < F_t$ it can grow arbitrarily large.
- The MAPE is biased towards underestimating values.

I've been using the `torchmetrics.MeanAbsolutePercentageError` for a regression problem but faced these challenges. That's when I decided to optimize my model with the squared logratio metric instead alleviating both issues.

### Pitch

With this issue I would like to figure out whether people are interested in me setting up a PR and possibly integrating the squared logratio into `torchmetrics`.

### Alternatives

The `torchmetrics.MeanAbsolutePercentageError` does a similar job but has problems as described above.

### Reference

 [https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2635088](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2635088)

**Comment by Borda** [comment]
@jsappl are you interested in adding this metric? :rabbit:

**Comment by jsappl** [comment]
Yes, I'd be willing to do that. I just posted this issue to follow the contribution guidelines :sweat_smile:

**Comment by jsappl** [comment]
While going through various metrics I found that the `MeanSquaredLogError` does exactely what I want. Since this metric is minimal when
```math
\text{MSLE} = \frac{1}{N} \sum_i ^N \big(\log(1+y_i) - \log (1+\hat y_i)\big)^2 = 0 \iff \forall\,i=1,\ldots,N\colon \big( \log(1+y_i) - \log (1+\hat y_i) \big)^2 = 0
```
and
```math
\log(1+y_i) - \log (1+\hat y_i)  = \log \Big( \frac{1+y_i}{1+\hat y_i} \Big) = 0 \iff \frac{1+y_i}{1+\hat y_i} = 1 \iff y_i = \hat y_i
```
there is no need to implement the metric I've mentioned above. I can just use the `MeanSquaredLogError` instead. Thanks for the effort though.
