### ISSUE TITLE
Standardize modular documentation

### ISSUE THREAD

**Issue by SkafteNicki** [Lightning-AI/metrics#1365]
## 📚 Documentation

Similar to the work done in this PR:
https://github.com/Lightning-AI/metrics/pull/1360

We want to standardize the way documentation is organised for modular metrics. This includes:
* `update` and `compute` are excluded from docs as the docstrings are often not meaningful to begin with. Instead information about input/output tensors should be included in the class docstring
* references are moved to the `links.rst` file
* Sections are organised as
  - Introduction to metric
  - Input/output format
  - Args
  - Raises
  - examples  
* shape information is formatted as \`\`(N, d)\`\` (normal brackets and double ticks)
* math if formatted using the :math: directive

Some of the points also apply to the functional backend, but the modular backend is of most importance because it has the largest variance in how information is organised currently.

Following domains needs to be taken care of

* [x] Aggregation -> #1369
* [x] Audio -> #1360
* [x] Classification -> #1433 
* [x] Image -> #1407
* [x] Detection -> #1372 
* [x] Regression -> #1410 
* [x] Retrieval -> #1429
* [x] Text -> #1416 

Any contributions are welcome :]

**Comment by theja-vanka** [comment]
Hi, Please assign Detection task to me. A bit of grooming will be helpful to deliver asap.

**Comment by reaganjlee** [comment]
All the docs should have been addressed now, let me know if there's anything else
