### ISSUE TITLE
pyright prompts import error

### ISSUE THREAD

**Issue by ZachVec** [Lightning-AI/metrics#1368]
## 🐛 Bug

As mentioned in [microsoft/pyright#2639](https://github.com/microsoft/pyright/issues/2639), there are private imports in `torchmetrics`'s subpackages.

### To Reproduce

1. Have `torch` and `torchmetrics` installed.
2. Create `test.py` in an empty folder.
3. write `from torchmetrics import F1Score` in `test.py`.
4. Then the pyright will prompt error says `"F1Score" is not exported from module "torchmetrics.classification", Import from "torchmetrics.classification.f_beta" instead (Pyright reportPrivateImportUsage)`

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/75198239/204999588-ce97064d-27d3-4e7e-8281-2ddd040d16a0.png">

#### Code sample

```python
from torchmetrics import F1Score
```

### Expected behavior

No error is expected.

### Environment

- TorchMetrics version (and how you installed TM, e.g. `conda`, `pip`, build from source):  0.10.3, installed through conda.
- Python & PyTorch Version (e.g., 1.0): 3.10.6
- Any other relevant information such as OS (e.g., Linux): Linux.

### Additional context

It's true that `torchmetrics/__init__.py`  containts `__all__` list which has all the classes and variable to be exported. But the subpackage doesn't do so. To illustrate, the `torch.classification` subpackage (the torch.classification.__init__.py file) neither include variables in `__all__` list nor use a redundant aliased import like `from torchmetrics.classification.f_beta import F1Score as F1Score`.

**Comment by Borda** [comment]
Hi @ZachVec, mind sending a draft PR with a suggested fix?

**Comment by ZachVec** [comment]
> Hi @ZachVec, mind sending a draft PR with a suggested fix?

I've noticed that this bug had been fixed in pull request [#1256 ](https://github.com/Lightning-AI/metrics/pull/1256). The `__all__`  list in `torchmetrics/classification/__init__.py` of that PR fixed this bug.
