### ISSUE TITLE
Using torch.float16 on pairwise_manhattan_distance gives NaN or INF

### ISSUE THREAD

**Issue by atharvjairath** [Lightning-AI/metrics#1380]
## 🐛 Bug
First of all, great work, made it easier for me to use. Thanks 
I was using torch.float32 vectors to compare pairwise_manhattan_distance and it was working fine.
I reduced the vector to half() (torch.float16), now pairwise_manhattan_distance gives NaN or INF

### To Reproduce

Steps to reproduce the behavior...
```python
from torchmetrics.functional import pairwise_manhattan_distance
# Works fine
print(pairwise_manhattan_distance(torch.reshape(query1_same,shape = (1,3485696))
,torch.reshape(query2_same,shape = (1,3485696))
))

# tensor([[495442.4688]])

print(pairwise_manhattan_distance(torch.reshape(query1_same.half(),shape = (1,3485696))
,torch.reshape(query2_same.half(),shape = (1,3485696))
))
#tensor([[inf]], dtype=torch.float16)
```

**Comment by SkafteNicki** [comment]
Hi @atharvjairath, thanks for reporting this issue.
Essentially  you are running into the restriction on the `half` dtype. The maximum value that can be represented with half precision is 65504. Such if you input two tensors where the summed abs difference is larger than 65504 then you get `inf`. A simple example:
![image](https://user-images.githubusercontent.com/24896311/206679791-5ede18d5-4f75-46b4-9a99-d9c9ed1deb34.png)
@Borda @justusschock is this something we want to fix by explicit casting to `float` before the computation or this just restriction by the datatype.

**Comment by SkafteNicki** [comment]
You could rescale your observations and then do the computation:
![image](https://user-images.githubusercontent.com/24896311/206855117-9280f348-f2f2-41a5-ad46-ce204801524e.png)
In this example, everything works when just computing with default float32 precision. When I transfer to float16 I get `inf` as you also report. However, if I rescale my observations, do the computation, cast back to float and then upscale the result then I get close to what I originally computed.
There is no way around that float16 does not have the same amount of precision at float32. Alternative to all this is to do the computation on CPU.

I am going to close the issue, as there is not really a bug here but it is just a consequence of the float16 datatype.
