### ISSUE TITLE
All links to source code are broken on readthedocs

### ISSUE THREAD

**Issue by is-jlehrer** [Lightning-AI/metrics#1394]
## 📚 Documentation

With the new torchmetrics==0.11 update, all of the "source" links are dead. For example, [Specificity](https://torchmetrics.readthedocs.io/en/stable/classification/specificity.html) source leads to [this page](https://github.com/Lightning-AI/metrics/blob/envs/stable/lib/python3.8/site-packages/torchmetrics/classification/specificity.py#L290-L340) which is dead.

All other metrics are the same.

**Comment by Borda** [comment]
@is-jlehrer are you interested in taking this issue as we have now enabled building RTFD within PR you shall be able to check the status of the doc after edit... :rabbit:
