### ISSUE TITLE
dice coefficient and f1score are different names of same cocept.

### ISSUE THREAD

**Issue by Freed-Wu** [Lightning-AI/metrics#1403]
See <https://en.wikipedia.org/wiki/Sørensen–Dice_coefficient>:

> Other names include:
>  [F1 score](https://en.wikipedia.org/wiki/F1_score)

Why not add some instruction to the document to let the reader know? Or the repeated code should be removed?

**Comment by Borda** [comment]
@Freed-Wu thank you for your comment, juts not sure if I follow, but could yo a bit more elaborate what is your suggestions? :rabbit:

**Comment by Freed-Wu** [comment]
1. If dice and f1 are same metrics, should the repeated code be removed?
2. If both of their codes are reserved, should some tips be added to let reader know?

**Comment by SkafteNicki** [comment]
Hi @Freed-Wu,
You are completely right and we have already discussed this internally. In PR https://github.com/Lightning-AI/metrics/pull/1090 the goal is to deprecate Dice Score (plus adding a reference in F1 score than it is also known as dice) and instead we are going to have a generalized dice score metric.

**Comment by Freed-Wu** [comment]
OK, close this issue because #1090.
