### ISSUE TITLE
Support for MetricTracker of MultioutputWrapper

### ISSUE THREAD

**Issue by ValerianRey** [Lightning-AI/metrics#1409]
## 🚀 Feature

Currently, `MetricTracker` works in the following cases:

- The base metric is of type `Metric`, and its `compute` method returns a single `Tensor`
- The base metric is of type `MetricCollection` and its `compute` method returns a `dict[str, Tensor]`

I would like to add support for two other cases which I came across in my projects:

- The base metric is of type `MultioutputWrapper`. Note that `MultioutputWrapper` is a subclass of `Metric`, but it is not supported by `MetricTracker` because its `compute` method returns a `List[Tensor]` rather than a single `Tensor`.
- The base metric is a `MetricCollection` of `MultioutputWrapper`. In thise case the `compute` method returns a `dict[str, List[Tensor]]`.

### Motivation

- I use `MultioutputWrapper` quite a lot for multi-regression problems. If I want to track its evolution over the epochs, I need to use a `MetricTracker` of `MultioutputWrapper`. 
- In some cases, I want to track multiple metrics (like MSE, MAE) for each of the outputs of my models, so I need to use a `MetricTracker` of `MetricCollection` of `MultioutputWrapper`.

### Pitch

After looking at the code, here is my proposed solution:
- Change `MetricTracker`'s `compute_all` method to support both of the new cases mentioned above.
- Change `MetricTracker`s `best_metric` method to support both of the new cases mentioned above.

### Alternatives

Add a boolean parameter to `MetricTracker` to make it return a `Tensor` of higher dimension rather than a `List[Tensor]`.

I don't really know which solution is best so I'll try to implement both in 2 different branches.

**Comment by ValerianRey** [comment]
After some thinking, I prefer the alternative solution:
> Make MetricTracker's compute_all function work when the underlying metric's compute function returns a list of tensors.

I'll start working on that to see if it could work like that.

**Comment by ValerianRey** [comment]
After looking at the code and starting to implement a solution, I completely updated the issue's description to make it much more clear.

**Comment by SkafteNicki** [comment]
Hi @ValerianRey,
Just wanted to check in how much process you had on this issue? it seems you commit a lot of code that references this issue. Is it close to done or do you want me to take a stab at it :)

**Comment by ValerianRey** [comment]
I added some new tests and the solution that makes them work when using a MetricTracker of MultioutputWrapper or a MetricTracker of MetricCollection of MultioutputWrapper. 

Everything works, but I don't like it this way. The MetricTracker class becomes too complex for what it does. The return type of best_metric becomes even more complex for example: 12 possible return types.

I think this class needs some deep changes before we invest too much development into it (some changes that would not make it backward-compatible).
For now, we could just specify in the documentation  which use-cases of MetricTracker work.
