### ISSUE TITLE
Confusion around logging and resetting

### ISSUE THREAD

**Issue by davidgilbertson** [Lightning-AI/metrics#1411]
## 🐛 Bug

I'm not sure if this is an error in the docs, error in the behaviour, or if I'm misunderstanding something.

This is about the idea ([from the docs](https://torchmetrics.readthedocs.io/en/stable/pages/lightning.html#logging-torchmetrics)) that if you pass a `Metric` object to `self.log()` of a `LightningModule`, the logging mechanism will perform the correct `.reset()` procedure for you, but if you _don't_ pass a metric to `self.log()` you must implement the resetting yourself.

A few comments:
* Is this correct? It seems like an odd separation of concerns to have the logging mechanism resetting metrics, and metrics producing incorrect results if not passed to the logging mechanism.
* From looking in the source and setting breakpoints, it seems that `.reset()` is called just fine without passing the metric to `self.log()`, but the docs seem to quite clearly state that this is not something I should be doing, so I'm not confident in my results.

My specific use case is that I have a `Trainer` callback that logs whatever `train_setp`/`validation_step` return. So I don't want to use `self.log()` inside my module, just calculate my loss/accuracy and return it.

**Comment by SkafteNicki** [comment]
Hi @davidgilbertson , thanks for your questions.

>     * Is this correct? It seems like an odd separation of concerns to have the logging mechanism resetting metrics, and metrics producing incorrect results if not passed to the logging mechanism.

Yes that is correct. The reason here being that we cannot assume when users actually want to reset their metrics. Assume you have a metric for validation and one for training. If we just autodetect and reset all objects of class `Metric` at the end of a training epoch it does not work for users where they are evaluating multiple times during a single epoch.
For this reason (and others) we need the user to explicitly call `self.log` on the metric object. In this way we know if it is a training/validation/test metric object (based on which `*_step` function it is called inside) and we can correctly reset at the right time.

>     * From looking in the source and setting breakpoints, it seems that `.reset()` is called just fine without passing the metric to `self.log()`, but the docs seem to quite clearly state that this is not something I should be doing, so I'm not confident in my results.

That should not be the case. Could you provide more info regarding this. I can find atleast one integration test here:
https://github.com/Lightning-AI/metrics/blob/b74d1cba74a9d29222afbbf61eb226889a8d588d/tests/integrations/test_lightning.py#L32-L62
that will fail if `metric.reset()` is not manually called.

> My specific use case is that I have a `Trainer` callback that logs whatever `train_setp`/`validation_step` return. So I don't want to use `self.log()` inside my module, just calculate my loss/accuracy and return it.

In that case I highly recommend to just call the metric manually and log the returned value and call reset manually.

**Comment by davidgilbertson** [comment]
Thanks @SkafteNicki, regarding the resetting appearing to happen, I might be misunderstanding things but I put a breakpoint in `Metric.reset()` and it's hit as a result of calculating the metric. [Here's the line that calls reset](https://github.com/Lightning-AI/metrics/blob/master/src/torchmetrics/metric.py#L302). Here's the stack trace:
![image](https://user-images.githubusercontent.com/4443482/209882875-4800d065-289f-46bb-9efe-dbe382372629.png)

**Comment by SkafteNicki** [comment]
Alright, then I understand the confusion. I assume that you call your metric like:
```python
self.metric(preds, target)
``
e.g. you call the `forward` method. The forward metric both computes the metric on the current batch and aggregate to the global state. We do this internally by calling `update`, `compute` and `reset` in the right order. You can read more about the details [here](https://torchmetrics.readthedocs.io/en/stable/pages/implement.html#internal-implementation-details) but essentially, it is correct that `reset` is called internally but the global state is still restored in that usecase.

Therefore you will still need to call `metric.reset()` yourself if you want to manually log metric values.

**Comment by davidgilbertson** [comment]
Ah, OK I think I get it, although I'm not sure about your last sentence. If I do:
```
acc = self.metric(preds, target)
```

In the `validation_step` then I can safely log the `acc` variable without worrying about calling `.reset()` right? Do you mean something else by "if you want to manually log metric values"?

I guess another way to phrase the question: if I call `self.accuracy_metric(preds, target)`, can I rely on it to return the accuracy _based only on the data I pass in_, or is there a scenario where calling it will also use cached data from previous calls and return the accuracy over all steps?

**Comment by SkafteNicki** [comment]
Hi @davidgilbertson,
If you call
```python
val = self.accuracy_metric(preds, target)
```
then `val` will ALWAYS only be based on the data that you pass in. What `forward` essentially is also doing, is that you for free can get the accumulated accuracy value over multiple batches by calling `self.metric.compute()` in the end.

**Comment by davidgilbertson** [comment]
Gotcha, thank you for the explanations.

I think I've found the part of the docs that got me confused, it's the phrase "this way" in "Note that logging metrics this way will require you to manually reset the metrics at the end of the epoch yourself" from [this page](https://torchmetrics.readthedocs.io/en/stable/pages/lightning.html#logging-torchmetrics).

I thought "this way" meant calculating the metric without passing the object to log. But "this way" specifically means using `.compute()` to get the aggregated value.

**Comment by SkafteNicki** [comment]
Sorry, for the long reply, but essentially yes, a manual reset is only necessary if you are interested in accumulating values over a given epoch, but still want the accumulation to reset between epochs. If you are just interested in the value on the current batch you are free to do as you like and I would even recommend that you just use the functional version of each metric, as the modular metrics are then essentially an over complication :)
Closing issue.
