### ISSUE TITLE
Return `class_names` as part of `MeanAveragePrecision.compute()`

### ISSUE THREAD

**Issue by manuelli** [Lightning-AI/metrics#1417]
## 🚀 Feature

Return the class names as part of `MeanAveragePrecision.compute()`.

### Motivation

 Currently only tensors are returned e.g. `map_per_class` and one cannot know which class the `map` corresponds to. It can happen that the `preds` and `targets` passed to `update` were missing a class, and then this class gets ignored when running `compute()` since metrics are computed only for classes that are seen during `update`, see [here](https://github.com/Lightning-AI/metrics/blob/bc057d495703aff5c4d8d671c54060e08a677142/src/torchmetrics/detection/mean_ap.py#L905)

### Pitch

Return the value of `self._get_classes` as part of the return dict in the [`compute`](https://github.com/Lightning-AI/metrics/blob/bc057d495703aff5c4d8d671c54060e08a677142/src/torchmetrics/detection/mean_ap.py#L877) call

### Alternatives

The current workaround is to use `self._get_classes()` to get this information. An alternative would be to make this function part of the public API.

**Comment by SkafteNicki** [comment]
Hi @manuelli,
I like this idea, but just to be more concrete could you provide an example with how the output of `.compute()` is looking for you right now and how you would prefer it to look?

**Comment by manuelli** [comment]
@SkafteNicki sure.


## Current return signature
Currently `map.compute()` returns a dict (see [docs](https://torchmetrics.readthedocs.io/en/stable/detection/mean_average_precision.html)) that contains only tensors. In particular it contains keys like `['map', 'map_per_class',...]`. The `map_per_class` tensor has shape `[N,]`. Suppose my model has `M=4` classes `[1,2,3,4]`. If class `3` never appeard in `preds` or `targets` during the `update` calls it will be the case that after calling `map.compute()` the `map._get_classes()` will return `[1,2,4]` and `map_per_class.shape = [3,]`. So in this case `N=3 < M=4` and the user has no way of knowing the mapping from entries of `map_per_class` to the class labels.

## Proposed return signature
I propose to also return the class labels as part of the return dict. So if  `d = map.compute()`  then it should contain a key `'classes'` that holds the value of `map._get_classes()`. Essentially you just need to add `'classes = self._get_classes()` to the dict that gets returned from `map.compute()`.

**Comment by SkafteNicki** [comment]
Hi @manuelli, thanks for the clarification. I created PR #1419 that will add `classes` to the output.
