### ISSUE TITLE
[Feature Request] Deterministic MulticlassAveragePrecision on GPU

### ISSUE THREAD

**Issue by starsholic** [Lightning-AI/metrics#1470]
## 🚀 Feature

Same as [Deterministic ConfusionMatrix](https://github.com/Lightning-AI/metrics/issues/880#issue-1164125314), for now, we cannot use `MulticlassAveragePrecision` with a lightning `Trainer` configured like this: `Trainer(gpus=1, deterministic=True)`.
The following error is returned:

```
File "./python3.9/site-packages/torchmetrics/functional/classification/precision_recall_curve.py", line 70, in _binary_clf_curve
    tps = torch.cumsum(target * weight, dim=0)[threshold_idxs]
RuntimeError: cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.
```

### Motivation

The idea would be to replace the call to torch.cumsum with something deterministic on GPU to properly use the GPU for metrics computation under a reproductible scenario (using a seed and deterministic flag).

### Pitch

Make sure that we can run the MulticlassAveragePrecision metric on GPU with deterministic algorithms.

### Alternatives

As an alternative, we can move the metric computation on cpu (instead of gpu) but this defeats the principle of having pure pytorch metrics.

### Additional context

I also found feature request in pytorch repo [issue](https://github.com/pytorch/pytorch/issues/89492)
As additional context, I have made a small script that produces the error:
```
import os

import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset

from pytorch_lightning import LightningModule, Trainer, seed_everything
from torchmetrics.classification import MulticlassAveragePrecision

class RandomDataset(Dataset):
    def __init__(self, size, length, num_classes=10):
        self.size = size
        self.len = length
        self.num_classes = num_classes

    def __getitem__(self, index):
        image = torch.rand(self.size, self.size, 3)
        label = torch.randint(low=0, high=self.num_classes, size=(1, ))
        return image, label

    def __len__(self):
        return self.len


class BoringModel(LightningModule):
    def __init__(self, num_classes=10):
        """Testing PL Module.

        Use as follows:
        - subclass
        - modify the behavior for what you want

        """
        super().__init__()
        self.layer_1 = torch.nn.Linear(32 * 32 * 3, 32)
        self.layer_1a = torch.nn.ReLU()
        self.layer_end = torch.nn.Linear(32, num_classes)

        self.val_multiclass_average_precision = MulticlassAveragePrecision(num_classes=num_classes, average='macro')



    def forward(self, x):
        """Forward."""
        x = torch.flatten(x, 1)
        x = self.layer_1(x)
        x = self.layer_1a(x)
        x = self.layer_end(x)
        return x

    def training_step(self, batch, batch_idx):
        """Training step."""
        labels = batch[1].squeeze(1)
        logits = self.forward(batch[0])
        loss = F.cross_entropy(logits, labels)
        self.log('Losses/Train_loss', loss, on_step=False, on_epoch=True)
        # self.log('Metrics/Train_accuracy', self.train_acc(logits, labels), on_step=False, on_epoch=True)
        # self.train_cm(logits, labels)
        return {"loss": loss}

    def validation_step(self, batch, batch_idx):
        """Validation step."""
        labels = batch[1].squeeze(1)
        logits = self.forward(batch[0])
        loss = F.cross_entropy(logits, labels)
        self.val_multiclass_average_precision(logits, labels)
        self.log("Validation mAP", self.val_multiclass_average_precision, on_epoch=True,
                 batch_size=len(batch))
        return {"x": loss}

    def configure_optimizers(self):
        """Configure optimizers."""
        optimizer = torch.optim.SGD(self.parameters(), lr=0.1)
        lr_scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=1)
        return [optimizer], [lr_scheduler]


def run():
    seed_everything(seed=42, workers=True)
    num_classes = 10
    train_data = DataLoader(RandomDataset(32, 64, num_classes=num_classes), batch_size=2)
    val_data = DataLoader(RandomDataset(32, 64, num_classes=num_classes), batch_size=2)

    model = BoringModel(num_classes=num_classes)
    trainer = Trainer(
        default_root_dir=os.getcwd(),
        limit_train_batches=1,
        limit_val_batches=1,
        num_sanity_val_steps=0,
        max_epochs=1,
        enable_model_summary=False,
        deterministic=True,
        gpus=1
    )
    trainer.fit(model, train_dataloaders=train_data, val_dataloaders=val_data)

if __name__ == "__main__":
    run()
```

**Comment by justusschock** [comment]
Hi @starsholic Thanks for the issue!
Can you show how much the results differ? If this is within expected numeric precision errors, we probably would not want another (potentially slower) implementation. Especially since on GPUs even `atomic_add` is not necessarily deterministic (which you would definitely need as operation).

**Comment by SkafteNicki** [comment]
I think that for now the better workaround is just to use the binned version of the metric by setting the `thresholds` argument, e.g. instead of doing:
```python
metric = MulticlassAveragePrecision(num_classes=3, thresholds=None, average="macro").cuda()
metric(torch.randn(100, 3).cuda(), torch.randint(3, (100,)).cuda())
```
which fails with the error, do
```python
metric = MulticlassAveragePrecision(num_classes=3, thresholds=10, average="macro").cuda()
metric(torch.randn(100, 3).cuda(), torch.randint(3, (100,)).cuda())
```
which works for me. You of cause need to set the thresholds arg appropriate based on your usecase.

**Comment by starsholic** [comment]
Hi @justusschock , thanks for your explanation! I have not yet compare the results differ caused by `cumsum`. It will cause slightly difference when I set `deterministic = false`, maybe it is caused by other non-deterministic operations.

**Comment by SpontaneousDuck** [comment]
It appears like this same issue is present on MeanAveragePrecision as well.

**Comment by starsholic** [comment]
@SkafteNicki Thanks a lot! I will have a try.

**Comment by SkafteNicki** [comment]
@SpontaneousDuck yes it will be a problem in all metrics that use `torch.cumsum` in their calculation. We cannot go around using it for some metrics. We could choose to provide a fallback solution as we do for some other metrics. I tested out few different methods for doing cumsum:
![image](https://user-images.githubusercontent.com/24896311/216081457-396855be-be08-4531-960f-a21a2476f384.png)
The only viable solution to me seems to be casting to cpu and calling `np.cumsum`. It is approx ~4 times slower than `torch.cumsum` and I am not sure if `np.cumsum` is deterministic.
@justusschock some opinions here? Especially, the question is if we should explicit deal with this or if just need to accept this being a limitation of torch.
