### ISSUE TITLE
Introduce k parameter in RetrievalMAP to compute at cut-off k

### ISSUE THREAD

**Issue by Bomme** [Lightning-AI/metrics#1491]
## 🚀 Feature

Add a parameter named `k` to RetrievalMAP to compute the mean average precision at cut-off k (e.g. MAP@10), i.e. consider only the top k elements for each query.

### Motivation

Other retrieval metrics such as (Precision and Recall) support limiting results to the top `k` returned results.
This is especially useful when calculating multiple different levels of cutoff for the same metric, e.g. P@1, P@5, P@10... 

### Pitch

Extend the modular metric and the functional interface of RETRIEVAL MEAN AVERAGE PRECISION (MAP) to compute the metric only from the top k elements of each query. By default all elements should be considered. 

### Alternatives

Not change the API and leave it to the user to limit the results.

**Comment by SkafteNicki** [comment]
@lucadiliello opinion here? is it a simple change to the codebase?

**Comment by lucadiliello** [comment]
Should be a simple change. @Bomme can you open a PR?

**Comment by Bomme** [comment]
Sure! I can prepare a PR.
