### ISSUE TITLE
Multiclass F1 score macro-average counts 0 if label does not occur

### ISSUE THREAD

**Issue by rubencart** [Lightning-AI/metrics#1494]
If I'm not mistaken, if you use `torchmetrics.functional.classification.multiclass_f1_score(preds, target, num_classes, average='macro')` with `num_classes` set to e.g. N, but some of these N classes do not occur in `preds` and `target`, the metric is 0 for these classes, which can significantly pull down the resulting macro average.
I don't know if this is the intended behavior or not, but it seems not very intuitive to me. If there is a problem with 5 classes, but you evaluate on a subset of the data in which only 3 of those classes occur, even when you predict perfectly, you won't get the maximum F1 score.
In any case, I think this should be explained in the documentation?

**Comment by JinhuaLiang** [comment]
I got the same issue. It seems that they encourage people to use torchmetric in the "{mode}_epoch_end()" style, although when I update the values and do computation in the very end, the result is still a little bit lower after many epochs than appending preds and targets in lists and computing them with a single function...

**Comment by JinhuaLiang** [comment]
> I got the same issue. It seems that they encourage people to use torchmetric in the "{mode}_epoch_end()" style, although when I update the values and do computation in the very end, the result is still a little bit lower after many epochs than appending preds and targets in lists and computing them with a single function...

is there anyway I can cache the preds and targets independently inside the metric class and do the computation when I call the compute() methods?

**Comment by rubencart** [comment]
I think in the best case the method should also return correct results when used on a subset of the data... :)
