### ISSUE TITLE
MulticlassExactMatch agnostic to 'ignore_index'

### ISSUE THREAD

**Issue by ItamarChinn** [Lightning-AI/metrics#1508]
## 🐛 Bug

In MulticlassExactMatch, `ignore_index` kwarg doesn't do anything.

### To Reproduce

Steps to reproduce the behavior...

```
>>> preds = torch.tensor([[1,1,1,2,2,2,2], [2,2,2,2,2,2,2]])
>>> target = torch.tensor([[1,1,1,2,-100,-100,-100], [1,1,2,2,-100,-100,-100]])
>>> preds
tensor([[1, 1, 1, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2]])
>>> target
tensor([[   1,    1,    1,    2, -100, -100, -100],
        [   1,    1,    2,    2, -100, -100, -100]])
>>> exact_match = MulticlassExactMatch(task='multiclass', num_classes=2, ignore_index=-100)
>>> exact_match.update(preds, target)
>>> exact_match.compute()
```

this should be 0.5 but it is 0

### Expected behavior

I expected it to ignore the locations where my target == -100

### Environment
Python 3.8.15
torchmetrics via pip '0.11.0'
torch '1.11.0+cu113'
Linux

**Comment by justusschock** [comment]
Hey @ItamarChinn, thank you for your issue. This indeed doesn't look correct. would you be interested in submitting a fix?

**Comment by ItamarChinn** [comment]
> Hey @ItamarChinn, thank you for your issue. This indeed doesn't look correct. would you be interested in submitting a fix?

Sure

**Comment by championsnet** [comment]
This needs fixing for multilabel exact match too
