### ISSUE TITLE
Extend Panoptic Quality usability, functionality and testing

### ISSUE THREAD

**Issue by marcocaccin** [Lightning-AI/metrics#1511]
## 🚀 Feature

Expand the [PanopticQuality](https://github.com/Lightning-AI/metrics/blob/master/src/torchmetrics/detection/panoptic_quality.py) code to
- allow batches in input (necessary feature)
- allow it to work on both images and point clouds (other inputs TBD)
- do not consider never seen classes in metric computation
- extend testing
- [let's see if something else comes up in the discussion here]

### Motivation

The just landed [PanopticQuality](https://github.com/Lightning-AI/metrics/blob/master/src/torchmetrics/detection/panoptic_quality.py) is a welcome addition to the toolbox, but there are a number of minor issues associated with it, from deal-breaking (does not take batches as inputs) to unnecessarily restrictive (PQ is a metric for panoptic segmentation both in point cloud and image domains), to suboptimal in terms of interpretability (if a class has TP + FP + FN = 0, why should it contribute to the final metric value?)

### Pitch

Let's bring in these goodies, happy to contribute 😉

**Comment by bhack** [comment]
I will add:
- cover  the Panoptic boundaries https://github.com/Lightning-AI/metrics/issues/50#issuecomment-1428755119
