### ISSUE TITLE
0.11.2 and 0.11.3 not released on PyPI

### ISSUE THREAD

**Issue by adamjstewart** [Lightning-AI/metrics#1571]
The 0.11.2 and 0.11.3 releases have both been released on GitHub, but haven't yet been released on PyPI. Is this planned for the future, or is the release process broken?

**Comment by adamjstewart** [comment]
Looks like they're there now, thanks!

**Comment by Borda** [comment]
yes we had a bug in pkg creation so I did it manually and fixing it in #1572
