### ISSUE TITLE
Lightning v2.0 training_step_end() removal

### ISSUE THREAD

**Issue by mwalmsley** [Lightning-AI/metrics#1632]
## 📚 Documentation

Lighting v2.0 [removes](https://github.com/Lightning-AI/lightning/releases/tag/2.0.0)
- training_epoch_end(outputs), etc methods, in favor of self.outputs and on_training_epoch_end()
- training_step_end(outputs) methods
- DP support

The [Use With Lightning](https://torchmetrics.readthedocs.io/en/stable/pages/lightning.html) torchmetrics docs currently tells users to use `training_epoch_end` etc. as a general example and `training_step_end` etc. with DP. These now no longer work.

I'm happy to make a small PR updating the docs page if helpful. In my own code, I've switched to updating and logging metrics with on_train_batch_end(outputs) with step=False, which I think should be equivalent to the older behavour - but I'm not an expert on TM.

**Comment by SkafteNicki** [comment]
Hi @mwalmsley, thanks for raising this issue.
I created PR #1633 to update the documentation.
