### ISSUE TITLE
Make Dice a ModuleMetric similar to IoU

### ISSUE THREAD

**Issue by seannz** [Lightning-AI/metrics#387]
## 🚀 Feature
Make Dice a ModuleMetric similar to IoU

### Motivation

Currently, the usability of Dice (functional metric) is no on par with that of (modular metric) IoU.

### Pitch

Making Dice a Module similar to IoU would greatly improve the usability of Dice

**Comment by brambozz** [comment]
Can I pick this one up? Was just looking for this functionality for my own project :)

**Comment by aseemk98** [comment]
Hi, is this issue still open?

**Comment by brambozz** [comment]
Seems like this is implemented already? https://torchmetrics.readthedocs.io/en/stable/classification/dice.html

So this can probably be closed.
