### ISSUE TITLE
OvO support on AUROC

### ISSUE THREAD

**Issue by chris-tkinter** [Lightning-AI/metrics#604]
## 🚀 Feature
Hi in the sklearn API there is a `multi_class` parameters which can be set to ‘ovr or ‘ovo'. But it seems that this is not yet implemented in the torchmetrics.

### Motivation

In sklearn we can compute ovo AUC, but currently this is not supported

```python
tm = AUROC(num_classes=7, average='macro')
x = torch.randn(100, 7).softmax(1)
y = torch.randint(7, (100, ))
print(tm(x, y), roc_auc_score(y, x, average="macro", multi_class="ovo"))
```

### Additional context
Using torchmetrics 0.6.0

**Comment by SkafteNicki** [comment]
Issue will be closed by classification refactor: see this issue https://github.com/Lightning-AI/metrics/issues/1001 and this PR https://github.com/Lightning-AI/metrics/pull/1195 for all changes

Small recap: This issue ask for support that `one-vs-one` approach for calculating `auroc` in multiclass settings. During the refactor it was determined that we do not want to pursue this approach and still only support `one-vs-the-rest` for calculating `roc`, `auroc` etc.

Issue will be closed when https://github.com/Lightning-AI/metrics/pull/1195 is merged.

**Comment by OmerShubi** [comment]
> It was determined that we do not want to pursue this approach and still only support one-vs-the-rest for calculating roc, auroc etc.

Would it be possible to add this clarification to the docs?

Currently it is not clear (to me) what is the multiclass approach that is place (one-vs-one/one-vs-rest).

Thanks!
