### ISSUE TITLE
Support basic plotting for some metrics

### ISSUE THREAD

**Issue by SkafteNicki** [Lightning-AI/metrics#652]
## 🚀 Feature

Add plotting functionality for metrics where it makes sense.

### Motivation

Some metrics like confusion matrix, roc, pr-curve are non-scalar metrics that are best inspected when plotted. 
It would be great if we could support some basic functionality for metrics where it makes sense to plot something (there are probably not that many).

### Pitch

Either have a utility module:
```python
from torchmetrics.utils.plotting import plot_confusion_matrix
metric = ConfusionMatrix()
output = metric(preds, target)
plot_confusion_matrix(output)
```
or incorporate directly into each modular metric
```python
metric = ConfusionMatrix()
output = metric(preds, target)
metric.plot(output)
```

### Alternatives

Keep as it is.

**Comment by andredantasrocha** [comment]
hi guys, any updates on this? it would be amazing to have a feature like that :)
