### ISSUE TITLE
Disentanglement Metrics

### ISSUE THREAD

**Issue by davidetalon** [Lightning-AI/metrics#883]
## 🚀 Feature
Add disentanglement metrics

### Motivation
Disentanglement metrics might be helpful to understand the properties of the learnt representation.

### Metrics
Disentanglement is still an ambiguous concept, some alternatives might be:
- [ ] BetaVAE [ArXiv](https://openreview.net/forum?id=Sy2fzU9gl)
- [ ] FactorVAE [ArXiv](https://arxiv.org/abs/1802.05983)
- [ ] Mutual Information Gap [ArXiv](https://arxiv.org/abs/1802.04942)
- [ ] DCI Disentanglement [ArXiv](https://openreview.net/forum?id=By-7dz-AZ)
- [ ] SAP Score [ArXiv](https://arxiv.org/abs/1711.00848)
- [ ]  ELBO [ArXiv](https://arxiv.org/abs/1312.6114)

### Additional context

Helpful resources are:
* [disentanglement_lib](https://github.com/google-research/disentanglement_lib)
* [Locatello2019Challenging](https://arxiv.org/abs/1811.12359) (see Appendix C)

**Comment by davidetalon** [comment]
I am open to help :)

**Comment by Borda** [comment]
Very nice! how about choosing one which you think is the most valuable and drafting a PR?
cc: @SkafteNicki @stancld

**Comment by davidetalon** [comment]
Thank you @Borda!  A good all around metric is DCI Disentanglement!
If there are no problems, I would start with it!

**Comment by Borda** [comment]
> If there are no problems, I would start with it!

cool pls send out your first PR :)

**Comment by davidetalon** [comment]
> > If there are no problems, I would start with it!
> 
> cool pls send out your first PR :)

I am sorry for being late. I am working on it! If you don't mind I would open the draft PR next week :)
