### ISSUE TITLE
Total Variation Loss

### ISSUE THREAD

**Issue by ragavvenkatesan** [Lightning-AI/metrics#972]
## 🚀 Feature

Hi, in the image package, we are missing the [total variation loss](https://en.wikipedia.org/wiki/Total_variation_denoising).

### Motivation

Total variation loss is a useful loss in reconstruction models such as in auto-encoders. Traditionally used in denoising, it is now being used in several other types of hi-res reconstruction.

**Comment by stancld** [comment]
Hi @ragavvenkatesan, looks like a good addition. Do you wanna try to tackle this one and send a PR? :]

**Comment by ragavvenkatesan** [comment]
> Hi @ragavvenkatesan, looks like a good addition. Do you wanna try to tackle this one and send a PR? :]

Sure. I can try and add. I have a version of this that I use already, which is `subclassed` from the Metric class.
